language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g gulp

script:
  - gulp

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
